### ISSUE TITLE
Build fails over git access rights to git@github.com:solo-io/envoy-common

### ISSUE THREAD

**Issue by sirajmansour** [solo-io/envoy-nats-streaming#62]
Really cool work here, i'm very interested in testing this in our pipeline. However the build is failing :(.
Below are the logs :

> Building in /home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf19                              a9/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/cares.dep.build, l                              ogs at /home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf19a9/ex                              ternal/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/cares.dep.log
> INFO: Repository rule 'com_google_absl' returned: {"remote": "https://github.com                              /abseil/abseil-cpp", "commit": "92e07e5590752d6b8e67f7f2f86c6286561e8cea", "shal                              low_since": "2018-01-08", "init_submodules": False, "verbose": False, "strip_pre                              fix": "", "patches": [], "patch_tool": "patch", "patch_args": ["-p0"], "patch_cm                              ds": [], "name": "com_google_absl"}
> ERROR: /home/siraj/repos/envoy-nats-streaming/source/extensions/filters/http/nat                              s/streaming/BUILD:46:1: no such package '@solo_envoy_common//source/common/http'                              : Traceback (most recent call last):
>         File "/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf                              19a9/external/bazel_tools/tools/build_defs/repo/git.bzl", line 146
>                 _clone_or_update(ctx)
>         File "/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf                              19a9/external/bazel_tools/tools/build_defs/repo/git.bzl", line 64, in _clone_or_                              update
>                 fail(("error cloning %s:\n%s" % (ctx....)))
> error cloning solo_envoy_common:
> + cd /home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf19a9/exte                              rnal
> + rm -rf /home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf19a9/                              external/solo_envoy_common /home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4                              bc05a2305cedf19a9/external/solo_envoy_common
> + git clone git@github.com:solo-io/envoy-common /home/siraj/.cache/bazel/_bazel_                              siraj/3e994dca8529ee4bc05a2305cedf19a9/external/solo_envoy_common
> Cloning into '/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf                              19a9/external/solo_envoy_common'...
> Host key verification failed.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> + git clone git@github.com:solo-io/envoy-common /home/siraj/.cache/bazel/_bazel_                              siraj/3e994dca8529ee4bc05a2305cedf19a9/external/solo_envoy_common
> Cloning into '/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf                              19a9/external/solo_envoy_common'...
> Host key verification failed.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
>  and referenced by '//source/extensions/filters/http/nats/streaming:nats_streami                              ng_filter_lib'
> ERROR: /home/siraj/repos/envoy-nats-streaming/source/extensions/filters/http/nat                              s/streaming/BUILD:46:1: no such package '@solo_envoy_common//source/common/http'                              : Traceback (most recent call last):
>         File "/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf                              19a9/external/bazel_tools/tools/build_defs/repo/git.bzl", line 146
>                 _clone_or_update(ctx)
>         File "/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf                              19a9/external/bazel_tools/tools/build_defs/repo/git.bzl", line 64, in _clone_or_                              update
>                 fail(("error cloning %s:\n%s" % (ctx....)))
> error cloning solo_envoy_common:
> + cd /home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf19a9/exte                              rnal
> + rm -rf /home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf19a9/                              external/solo_envoy_common /home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4                              bc05a2305cedf19a9/external/solo_envoy_common
> + git clone git@github.com:solo-io/envoy-common /home/siraj/.cache/bazel/_bazel_                              siraj/3e994dca8529ee4bc05a2305cedf19a9/external/solo_envoy_common
> Cloning into '/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf                              19a9/external/solo_envoy_common'...
> Host key verification failed.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> + git clone git@github.com:solo-io/envoy-common /home/siraj/.cache/bazel/_bazel_                              siraj/3e994dca8529ee4bc05a2305cedf19a9/external/solo_envoy_common
> Cloning into '/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf                              19a9/external/solo_envoy_common'...
> Host key verification failed.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
>  and referenced by '//source/extensions/filters/http/nats/streaming:nats_streami                              ng_filter_lib'
> ERROR: Analysis of target '//:envoy' failed; build aborted: no such package '@so                              lo_envoy_common//source/common/http': Traceback (most recent call last):
>         File "/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf                              19a9/external/bazel_tools/tools/build_defs/repo/git.bzl", line 146
>                 _clone_or_update(ctx)
>         File "/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf                              19a9/external/bazel_tools/tools/build_defs/repo/git.bzl", line 64, in _clone_or_                              update
>                 fail(("error cloning %s:\n%s" % (ctx....)))
> error cloning solo_envoy_common:
> + cd /home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf19a9/exte                              rnal
> + rm -rf /home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf19a9/                              external/solo_envoy_common /home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4                              bc05a2305cedf19a9/external/solo_envoy_common
> + git clone git@github.com:solo-io/envoy-common /home/siraj/.cache/bazel/_bazel_                              siraj/3e994dca8529ee4bc05a2305cedf19a9/external/solo_envoy_common
> Cloning into '/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf                              19a9/external/solo_envoy_common'...
> Host key verification failed.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> + git clone git@github.com:solo-io/envoy-common /home/siraj/.cache/bazel/_bazel_                              siraj/3e994dca8529ee4bc05a2305cedf19a9/external/solo_envoy_common
> Cloning into '/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf                              19a9/external/solo_envoy_common'...
> Host key verification failed.
> fatal: Could not read from remote repository.
> 
>

**Comment by yuval-k** [comment]
Try changing the envoy common gt repository in the WORKSPACE file from ssh
url to https url.

I.e. in line 17, instead of
git@github.com:solo-io/envoy-common
Try:
https://github.com/solo-io/envoy-common

On Aug 23, 2018 10:23 PM, "sirajmansour" <notifications@github.com> wrote:

Really cool work here, i'm very interested in testing this in our pipeline.
However the build is failing :(.
Below are the logs :

Building in
/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf19
a9/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/cares.dep.build,
l ogs at
/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf19a9/ex
ternal/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/cares.dep.log
INFO: Repository rule 'com_google_absl' returned: {"remote": "
https://github.com /abseil/abseil-cpp", "commit":
"92e07e5590752d6b8e67f7f2f86c6286561e8cea", "shal low_since": "2018-01-08",
"init_submodules": False, "verbose": False, "strip_pre fix": "", "patches":
[], "patch_tool": "patch", "patch_args": ["-p0"], "patch_cm ds": [],
"name": "com_google_absl"}
ERROR:
/home/siraj/repos/envoy-nats-streaming/source/extensions/filters/http/nat
s/streaming/BUILD:46:1: no such package
'@solo_envoy_common//source/common/http' : Traceback (most recent call
last):
File "/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf
19a9/external/bazel_tools/tools/build_defs/repo/git.bzl", line 146
_clone_or_update(ctx)
File "/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf
19a9/external/bazel_tools/tools/build_defs/repo/git.bzl", line 64, in
*clone_or* update
fail(("error cloning %s:\n%s" % (ctx....)))
error cloning solo_envoy_common:

   - cd
   /home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf19a9/exte
   rnal
   - rm -rf
   /home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf19a9/
   external/solo_envoy_common
   /home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4
   bc05a2305cedf19a9/external/solo_envoy_common
   - git clone git@github.com:solo-io/envoy-common /home/siraj/.cache/bazel/
   *bazel* siraj/3e994dca8529ee4bc05a2305cedf19a9/external/solo_envoy_common
   Cloning into
   '/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf
   19a9/external/solo_envoy_common'...
   Host key verification failed.
   fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

   - git clone git@github.com:solo-io/envoy-common /home/siraj/.cache/bazel/
   *bazel* siraj/3e994dca8529ee4bc05a2305cedf19a9/external/solo_envoy_common
   Cloning into
   '/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf
   19a9/external/solo_envoy_common'...
   Host key verification failed.
   fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
and referenced by
'//source/extensions/filters/http/nats/streaming:nats_streami ng_filter_lib'
ERROR:
/home/siraj/repos/envoy-nats-streaming/source/extensions/filters/http/nat
s/streaming/BUILD:46:1: no such package
'@solo_envoy_common//source/common/http' : Traceback (most recent call
last):
File "/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf
19a9/external/bazel_tools/tools/build_defs/repo/git.bzl", line 146
_clone_or_update(ctx)
File "/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf
19a9/external/bazel_tools/tools/build_defs/repo/git.bzl", line 64, in
*clone_or* update
fail(("error cloning %s:\n%s" % (ctx....)))
error cloning solo_envoy_common:

   - cd
   /home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf19a9/exte
   rnal
   - rm -rf
   /home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf19a9/
   external/solo_envoy_common
   /home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4
   bc05a2305cedf19a9/external/solo_envoy_common
   - git clone git@github.com:solo-io/envoy-common /home/siraj/.cache/bazel/
   *bazel* siraj/3e994dca8529ee4bc05a2305cedf19a9/external/solo_envoy_common
   Cloning into
   '/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf
   19a9/external/solo_envoy_common'...
   Host key verification failed.
   fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

   - git clone git@github.com:solo-io/envoy-common /home/siraj/.cache/bazel/
   *bazel* siraj/3e994dca8529ee4bc05a2305cedf19a9/external/solo_envoy_common
   Cloning into
   '/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf
   19a9/external/solo_envoy_common'...
   Host key verification failed.
   fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
and referenced by
'//source/extensions/filters/http/nats/streaming:nats_streami ng_filter_lib'
ERROR: Analysis of target '//:envoy' failed; build aborted: no such package
'@so <https://github.com/so> lo_envoy_common//source/common/http':
Traceback (most recent call last):
File "/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf
19a9/external/bazel_tools/tools/build_defs/repo/git.bzl", line 146
_clone_or_update(ctx)
File "/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf
19a9/external/bazel_tools/tools/build_defs/repo/git.bzl", line 64, in
*clone_or* update
fail(("error cloning %s:\n%s" % (ctx....)))
error cloning solo_envoy_common:

   - cd
   /home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf19a9/exte
   rnal
   - rm -rf
   /home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf19a9/
   external/solo_envoy_common
   /home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4
   bc05a2305cedf19a9/external/solo_envoy_common
   - git clone git@github.com:solo-io/envoy-common /home/siraj/.cache/bazel/
   *bazel* siraj/3e994dca8529ee4bc05a2305cedf19a9/external/solo_envoy_common
   Cloning into
   '/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf
   19a9/external/solo_envoy_common'...
   Host key verification failed.
   fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

   - git clone git@github.com:solo-io/envoy-common /home/siraj/.cache/bazel/
   *bazel* siraj/3e994dca8529ee4bc05a2305cedf19a9/external/solo_envoy_common
   Cloning into
   '/home/siraj/.cache/bazel/_bazel_siraj/3e994dca8529ee4bc05a2305cedf
   19a9/external/solo_envoy_common'...
   Host key verification failed.
   fatal: Could not read from remote repository.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/solo-io/envoy-nats-streaming/issues/62>, or mute the
thread

**Comment by yuval-k** [comment]
Try changing the envoy common gt repository in the WORKSPACE file from ssh url to https url.

I.e. in line 17, instead of
git@github.com:solo-io/envoy-common
Try:
https://github.com/solo-io/envoy-common

**Comment by sirajmansour** [comment]
works like a charm 👍 submit a PR ?

**Comment by yuval-k** [comment]
Yes please. Thank you
